
############# SCPDiscord configuration file #############


# Connection settings, the port cannot be the same as the SCPSL server port.
bot:
    ip: "127.0.0.1"
    port: 8888

    # Set which Discord activity should be used.
    # The options are one of the following:
    # Playing, Streaming, ListeningTo, Watching, Custom, Competing
    activity:
        empty:  "Custom"
        active: "Custom"
        full:   "Custom"

    # Set which Discord activity should be used.
    # The options are one of the following:
    # Offline, Online, Idle, DoNotDisturb, Invisible
    status:
        empty:  "Idle"
        active: "Online"
        full:   "Online"

settings:
    # The language is the same as the name of the language file you want to use.

    # Included languages:
    # english (default)
    # ukrainian
    # russian
    # simplified-chinese
    # italian

    # If you want to override specific messages you can copy them to overrides.yml
    # and they will automatically replace the corresponding messages from the language selected below
    language: "english"

    # Add an emote as a prefix to messages
    emotes: true

    # The message timestamp, see syntax guide here: https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings
    # You can set it to "HH:mm:ss" for a simple timestamp.
    timestamp: ""

    # Whether the plugin should send debug information in the console
    debug: false

    # Turns on the config validation which shows the values after they have been read by the plugin so you can see they are correct
    configvalidation: false

    # Whether or not to use the rolesync system
    rolesync: true

    # Whether files should be read from the global config directory or the local one (aka the server specific one).
    useglobaldirectory:
        language: true
        rolesync: true
        mutes: true
        timetracking: true

    # Always replace language and emote files when the plugin starts (does not affect overrides.yml and emote-overrides.yml).
    # Turn this off if you will be directly editing the language files.
    # If you are only making small edits to the language files it is highly
    # recommended to use overrides.yml instead of editing the language file.
    regeneratelanguagefiles: true

    # EXPERIMENTAL:
    # Whether SCPDiscord should automatically cause the game to reload certain files when they are changed by other servers
    autoreload:
        reservedslots: false
        whitelist: false

# Sets commands which are run whenever someone with a synced Discord rank joins the server,
# only the highest one in the list that matches the player is executed
# Turn on debug above to see console feedback when the commands are used
# Valid variables:
# player-userid
# player-id
# player-name
# player-ipaddress
# player-role
# player-team
# discorddisplayname
# discordusername
# discordusernamewithdiscriminator
# discordid
# There are some more player variables you can use here but they are mostly irrelevant, check the list in APIExtensions.cs on github for the full list.
rolesync:
    - "add-role-id-here":
        - "scpd grantvanillarank <var:player-userid> moderator"
        - "scpd grantreservedslot <var:player-userid> @<var:discordusername> (<var:discordid>)"
        - "/pbc <var:player-id> 3 Moderator role synced from Discord."

    - "add-another-role-id-here":
        - "scpd grantvanillarank <var:player-userid> donator"
        - "scpd grantreservedslot <var:player-userid> @<var:discordusername> (<var:discordid>)"
        - "/pbc <var:player-id> 3 Donator role synced from Discord."

    - "add-everyone-role-id-here":
        - "scpd removereservedslot <var:player-userid>"

# Name your channels here, this name is used in the channels section below.
# The left value is a name of your choice and the right is a channel id you want it to represent in the lists below.
channels:
    - "default": "add-channel-id-here"
    - "staff": "add-channel-id-here"

channelsettings:
    # If this is true, IPs and steamIDs will be blocked in all channels EXCEPT the channels listed below.
    # If this is set to false, IPs and steamIDs will be blocked ONLY in the channels listed below.
    invertfilters: true

    # Removes online players' IPs from discord messages in specific channels, use the channel aliases from above.
    # Warning: This only works on online players, so may fail on player disconnect related events
    filterips: [ "staff" ]

    # Replaces online players' SteamIDs with PlayerIDs in discord messages in specific channels, use the channel aliases from above.
    # Warning: This only works on online players, so may fail on player disconnect related events
    filtersteamids: [ "default", "staff" ]

# Using the channel aliases above you can direct events to different channels here
# Set to [] to disable an event.
messages:
    # Server events
    connectedtobot: [ "default", "staff" ]
    onroundstart: []
    onconnect: []
    onplayerleave: [ "default" ]
    onroundend: [ "default", "staff" ]
    onwaitingforplayers: [ "default" ]
    onroundrestart: [ "default", "staff" ]
    onsetservername: []
    onban:
        player: [ "default" ]
        server: [ "default" ]
    onbanissued:
        ip: [ "staff" ]
        userid: [ "staff" ]
    onbanupdated:
        ip: []
        userid: []
    onbanrevoked:
        ip: [ "staff" ]
        userid: [ "staff" ]
    onkick:
        player: [ "default", "staff" ]
        server: [ "default", "staff" ]
    onplayermuted:
        player:
            intercom: [ "default", "staff" ]
            standard: [ "default", "staff" ]
        server:
            intercom: [ "default", "staff" ]
            standard: [ "default", "staff" ]
    onplayerunmuted:
        player:
            intercom: [ "default", "staff" ]
            standard: [ "default", "staff" ]
        server:
            intercom: [ "default", "staff" ]
            standard: [ "default", "staff" ]
    oncallcommand:
        remoteadmin:
            player: []
            server: []
        game:
            player: []
            server: []
        console:
            player: []
            server: []
    onexecutedcommand:
        remoteadmin:
            player: [ "staff" ]
            server: [ "staff" ]
        game:
            player: [ "staff" ]
            server: [ "staff" ]
        console:
            player: [ "staff" ]
            server: [ "staff" ]
    onplayercheaterreport: [ "staff" ]
    onplayerreport: [ "staff" ]

    # Environment events
    onscp914activate: []
    onstartcountdown:
        player:
            initiated: [ "default" ]
            resumed: [ "default" ]
        server:
            initiated: [ "default" ]
            resumed: [ "default" ]
    onstopcountdown:
        default: [ "default" ]
        noplayer: [ "default" ]
    ondetonate: [ "default" ]
    ondecontaminate: [ "default" ]
    onsummonvehicle:
        chaos: [ "default" ]
        mtf: [ "default" ]
    ongeneratorfinish: [ "default" ]
    onelevatoruse: []

    ongeneratorunlock: [ "default" ]
    ongeneratoropen: []
    ongeneratorclose: []
    ongeneratoractivated: [ "default" ]
    ongeneratordeactivated: [ "default" ]
    onscp914changeknob: []
    onplayertriggertesla:
        default: []
        ignored: []
    onpocketdimensionexit: [ "default" ]
    onpocketdimensionenter: [ "default" ]
    ondooraccess:
        allowed: []
        denied: []

    # SCP Events
    on079lockdoor: []
    on079teslagate: []
    on079addexp: []
    on079levelup: [ "default" ]
    on079unlockdoor: []
    on079lockdown: []
    on079cancellockdown: []
    onrecallzombie: []
    onplayerinfected: [ "default" ]

    # Player events
    onplayerhurt:
        default: []
        friendlyfire: []
        noattacker: []
    onplayerdie:
        default: [ "default" ]
        friendlyfire: [ "default", "staff" ]
        nokiller: [ "default" ]
    onplayerpickupitem: []
    onplayerpickupammo: []
    onplayerpickuparmor: []
    onplayerpickupscp330: []
    onplayerdropitem: []
    onplayerdropammo: []
    onplayerjoin: [ "default", "staff" ]
    onnicknameset: []
    onsetrole:
        roundstart: [ "default" ]
        latejoin: [ "default" ]
        respawn: [ "default" ]
        died: []
        escaped: []
        revived: [ "default" ]
        remoteadmin: [ "default" ]
        left: []
        other: []
    onspawn: []
    onthrowprojectile: [ "default", "staff" ]
    onspawnragdoll: []
    onitemuse: [ "default" ]
    onhandcuff:
        default: [ "default" ]
        nootherplayer: [ "default" ]
    onhandcuffremoved:
        default: [ "default" ]
        nootherplayer: [ "default" ]
    onplayerradioswitch: []
    onreload: []
    ongrenadeexplosion: []
    ongrenadehitplayer: []
    onteamrespawn:
        mtf: [ "default" ]
        ci: [ "default" ]
    onplayerescape: [ "default" ]